spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yoon
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug

